// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/videotask"
)

// VideoTaskCreate is the builder for creating a VideoTask entity.
type VideoTaskCreate struct {
	config
	mutation *VideoTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoTaskCreate) SetCreatedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableCreatedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoTaskCreate) SetUpdatedAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableUpdatedAt(v *time.Time) *VideoTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *VideoTaskCreate) SetProvider(v string) *VideoTaskCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_c *VideoTaskCreate) SetUpstreamTaskID(v string) *VideoTaskCreate {
	_c.mutation.SetUpstreamTaskID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *VideoTaskCreate) SetAccountID(v int64) *VideoTaskCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *VideoTaskCreate) SetGroupID(v int64) *VideoTaskCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VideoTaskCreate) SetUserID(v int64) *VideoTaskCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *VideoTaskCreate) SetAPIKeyID(v int64) *VideoTaskCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *VideoTaskCreate) SetModel(v string) *VideoTaskCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoTaskCreate) SetStatus(v string) *VideoTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *VideoTaskCreate) SetNillableStatus(v *string) *VideoTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *VideoTaskCreate) SetExpiresAt(v time.Time) *VideoTaskCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the VideoTaskMutation object of the builder.
func (_c *VideoTaskCreate) Mutation() *VideoTaskMutation {
	return _c.mutation
}

// Save creates the VideoTask in the database.
func (_c *VideoTaskCreate) Save(ctx context.Context) (*VideoTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoTaskCreate) SaveX(ctx context.Context) *VideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoTaskCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videotask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videotask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := videotask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoTaskCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoTask.updated_at"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "VideoTask.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := videotask.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "VideoTask.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamTaskID(); !ok {
		return &ValidationError{Name: "upstream_task_id", err: errors.New(`ent: missing required field "VideoTask.upstream_task_id"`)}
	}
	if v, ok := _c.mutation.UpstreamTaskID(); ok {
		if err := videotask.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "VideoTask.upstream_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "VideoTask.account_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "VideoTask.group_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VideoTask.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "VideoTask.api_key_id"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "VideoTask.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := videotask.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "VideoTask.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoTask.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videotask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoTask.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "VideoTask.expires_at"`)}
	}
	return nil
}

func (_c *VideoTaskCreate) sqlSave(ctx context.Context) (*VideoTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoTaskCreate) createSpec() (*VideoTask, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videotask.Table, sqlgraph.NewFieldSpec(videotask.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videotask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videotask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(videotask.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.UpstreamTaskID(); ok {
		_spec.SetField(videotask.FieldUpstreamTaskID, field.TypeString, value)
		_node.UpstreamTaskID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(videotask.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(videotask.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(videotask.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(videotask.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(videotask.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videotask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(videotask.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTask.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskCreate) OnConflict(opts ...sql.ConflictOption) *VideoTaskUpsertOne {
	_c.conflict = opts
	return &VideoTaskUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskCreate) OnConflictColumns(columns ...string) *VideoTaskUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskUpsertOne{
		create: _c,
	}
}

type (
	// VideoTaskUpsertOne is the builder for "upsert"-ing
	//  one VideoTask node.
	VideoTaskUpsertOne struct {
		create *VideoTaskCreate
	}

	// VideoTaskUpsert is the "OnConflict" setter.
	VideoTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsert) SetUpdatedAt(v time.Time) *VideoTaskUpsert {
	u.Set(videotask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateUpdatedAt() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldUpdatedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsert) SetStatus(v string) *VideoTaskUpsert {
	u.Set(videotask.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsert) UpdateStatus() *VideoTaskUpsert {
	u.SetExcluded(videotask.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskUpsertOne) UpdateNewValues() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videotask.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Provider(); exists {
			s.SetIgnore(videotask.FieldProvider)
		}
		if _, exists := u.create.mutation.UpstreamTaskID(); exists {
			s.SetIgnore(videotask.FieldUpstreamTaskID)
		}
		if _, exists := u.create.mutation.AccountID(); exists {
			s.SetIgnore(videotask.FieldAccountID)
		}
		if _, exists := u.create.mutation.GroupID(); exists {
			s.SetIgnore(videotask.FieldGroupID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(videotask.FieldUserID)
		}
		if _, exists := u.create.mutation.APIKeyID(); exists {
			s.SetIgnore(videotask.FieldAPIKeyID)
		}
		if _, exists := u.create.mutation.Model(); exists {
			s.SetIgnore(videotask.FieldModel)
		}
		if _, exists := u.create.mutation.ExpiresAt(); exists {
			s.SetIgnore(videotask.FieldExpiresAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoTaskUpsertOne) Ignore() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskUpsertOne) DoNothing() *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskCreate.OnConflict
// documentation for more info.
func (u *VideoTaskUpsertOne) Update(set func(*VideoTaskUpsert)) *VideoTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsertOne) SetUpdatedAt(v time.Time) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateUpdatedAt() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsertOne) SetStatus(v string) *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsertOne) UpdateStatus() *VideoTaskUpsertOne {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *VideoTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoTaskUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoTaskUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoTaskCreateBulk is the builder for creating many VideoTask entities in bulk.
type VideoTaskCreateBulk struct {
	config
	err      error
	builders []*VideoTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoTask entities in the database.
func (_c *VideoTaskCreateBulk) Save(ctx context.Context) ([]*VideoTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoTaskCreateBulk) SaveX(ctx context.Context) []*VideoTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoTaskUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoTaskUpsertBulk {
	_c.conflict = opts
	return &VideoTaskUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoTaskCreateBulk) OnConflictColumns(columns ...string) *VideoTaskUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoTaskUpsertBulk{
		create: _c,
	}
}

// VideoTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoTask nodes.
type VideoTaskUpsertBulk struct {
	create *VideoTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoTaskUpsertBulk) UpdateNewValues() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videotask.FieldCreatedAt)
			}
			if _, exists := b.mutation.Provider(); exists {
				s.SetIgnore(videotask.FieldProvider)
			}
			if _, exists := b.mutation.UpstreamTaskID(); exists {
				s.SetIgnore(videotask.FieldUpstreamTaskID)
			}
			if _, exists := b.mutation.AccountID(); exists {
				s.SetIgnore(videotask.FieldAccountID)
			}
			if _, exists := b.mutation.GroupID(); exists {
				s.SetIgnore(videotask.FieldGroupID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(videotask.FieldUserID)
			}
			if _, exists := b.mutation.APIKeyID(); exists {
				s.SetIgnore(videotask.FieldAPIKeyID)
			}
			if _, exists := b.mutation.Model(); exists {
				s.SetIgnore(videotask.FieldModel)
			}
			if _, exists := b.mutation.ExpiresAt(); exists {
				s.SetIgnore(videotask.FieldExpiresAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoTaskUpsertBulk) Ignore() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoTaskUpsertBulk) DoNothing() *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoTaskCreateBulk.OnConflict
// documentation for more info.
func (u *VideoTaskUpsertBulk) Update(set func(*VideoTaskUpsert)) *VideoTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoTaskUpsertBulk) SetUpdatedAt(v time.Time) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateUpdatedAt() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStatus sets the "status" field.
func (u *VideoTaskUpsertBulk) SetStatus(v string) *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoTaskUpsertBulk) UpdateStatus() *VideoTaskUpsertBulk {
	return u.Update(func(s *VideoTaskUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *VideoTaskUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
